export const eras = [
  {
    id: 'ancient',
    title: 'Древний мир',
    period: '3500 до н.э. — 476 н.э.',
    gradient: 'from-amber to-crimson',
    summary:
      'Появление городов, письменности, империй, правовых систем, мировых религий и первых глобальных торговых маршрутов.',
    milestones: [
      'Шумерские города-государства и клинопись',
      'Египетские царства и монументальная архитектура',
      'Греческие полисы, философия и эллинизм',
      'Римская республика и империя',
      'Династии Цинь и Хань в Китае',
    ],
    regions: ['Месопотамия', 'Египет', 'Средиземноморье', 'Китай', 'Индия'],
  },
  {
    id: 'middle',
    title: 'Средневековье',
    period: '476 — 1492',
    gradient: 'from-emerald to-royal',
    summary:
      'Формирование феодальных обществ, исламского мира, Византии, европейских королевств, монгольских коммуникаций и университетов.',
    milestones: [
      'Византийская империя и сохранение античного наследия',
      'Распространение ислама и халифаты',
      'Крестовые походы и средиземноморская торговля',
      'Монгольская империя и Евразийская сеть путей',
      'Черная смерть и социальные изменения в Европе',
    ],
    regions: ['Европа', 'Ближний Восток', 'Центральная Азия', 'Китай', 'Африка'],
  },
  {
    id: 'early-modern',
    title: 'Раннее Новое время',
    period: '1492 — 1789',
    gradient: 'from-sky to-violet',
    summary:
      'Океанические открытия, колониальные империи, реформации, научная революция и начало мировой экономики.',
    milestones: [
      'Колумбов обмен и трансатлантические связи',
      'Османская, Сефевидская и Могольская державы',
      'Реформация и религиозные войны',
      'Научная революция',
      'Просвещение и новые политические идеи',
    ],
    regions: ['Атлантика', 'Европа', 'Америка', 'Южная Азия', 'Османский мир'],
  },
  {
    id: 'modern',
    title: 'Новое время',
    period: '1789 — 1945',
    gradient: 'from-rose to-gold',
    summary:
      'Революции, индустриализация, национализм, империализм и две мировые войны радикально меняют общества.',
    milestones: [
      'Французская революция и наполеоновские войны',
      'Индустриальная революция',
      'Объединение Италии и Германии',
      'Первая мировая война',
      'Вторая мировая война',
    ],
    regions: ['Европа', 'Америка', 'Япония', 'Африка', 'Ближний Восток'],
  },
  {
    id: 'contemporary',
    title: 'Современность',
    period: '1945 — наши дни',
    gradient: 'from-indigo to-cyan',
    summary:
      'Холодная война, деколонизация, интеграционные проекты, цифровая эпоха и новые формы глобальной взаимозависимости.',
    milestones: [
      'Создание ООН и послевоенный порядок',
      'Деколонизация Азии и Африки',
      'Холодная война и гонка вооружений',
      'Европейская интеграция',
      'Глобализация и цифровая революция',
    ],
    regions: ['Мир', 'США', 'СССР/Россия', 'Китай', 'Глобальный Юг'],
  },
];

export const countries = [
  {
    id: 'dz',
    name: 'Алжир',
    flag: '🇩🇿',
    region: 'Северная Африка',
    timeline: '1962 — наши дни',
    core: 'Независимость от Франции, социалистический период, гражданская война 1990-х, современная роль в Африке и исламском мире.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ao',
    name: 'Ангола',
    flag: '🇦🇴',
    region: 'Южная Африка',
    timeline: '1975 — наши дни',
    core: 'Португальская колонизация, война за независимость, гражданская война, нефть, роль в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bj',
    name: 'Бенин',
    flag: '🇧🇯',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Древняя империя Дагомея, французская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bw',
    name: 'Ботсвана',
    flag: '🇧🇼',
    region: 'Южная Африка',
    timeline: '1966 — наши дни',
    core: 'Британский протекторат Бечуаналенд, независимость, алмазы, стабильная демократия в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bf',
    name: 'Буркина-Фасо',
    flag: '🇧🇫',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Колония Верхняя Вольта, независимость, революция Томаса Санкары, современная роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bi',
    name: 'Бурунди',
    flag: '🇧🇮',
    region: 'Восточная Африка',
    timeline: '1962 — наши дни',
    core: 'Королевство Бурунди, немецкая и бельгийская колонизация, независимость, этнические конфликты.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cm',
    name: 'Камерун',
    flag: '🇨🇲',
    region: 'Центральная Африка',
    timeline: '1960 — наши дни',
    core: 'Немецкая колония, раздел между Францией и Великобританией, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cv',
    name: 'Кабо-Верде',
    flag: '🇨🇻',
    region: 'Западная Африка',
    timeline: '1975 — наши дни',
    core: 'Португальская колония, независимость, стабильная демократия, роль в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cf',
    name: 'Центральноафриканская Республика',
    flag: '🇨🇫',
    region: 'Центральная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония Убанги-Шари, независимость, политическая нестабильность, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'td',
    name: 'Чад',
    flag: '🇹🇩',
    region: 'Центральная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, политическая нестабильность, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'km',
    name: 'Коморы',
    flag: '🇰🇲',
    region: 'Восточная Африка',
    timeline: '1975 — наши дни',
    core: 'Французская колония, независимость архипелага Коморских островов, роль в Индийском океане.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cd',
    name: 'Демократическая Республика Конго',
    flag: '🇨🇩',
    region: 'Центральная Африка',
    timeline: '1960 — наши дни',
    core: 'Бельгийская колония, независимость, диктатура Мобуту, гражданская война, роль в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cg',
    name: 'Республика Конго',
    flag: '🇨🇬',
    region: 'Центральная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, социалистический период, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ci',
    name: 'Кот-д’Ивуар',
    flag: '🇨🇮',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость под руководством Уфуэ-Буаньи, экономическая роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'dj',
    name: 'Джибути',
    flag: '🇩🇯',
    region: 'Восточная Африка',
    timeline: '1977 — наши дни',
    core: 'Французская колония Французский Сомалиленд, независимость, стратегическое положение у Красного моря.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'eg',
    name: 'Египет',
    flag: '🇪🇬',
    region: 'Северная Африка',
    timeline: 'ок. 3100 до н.э. — наши дни',
    core: 'Одна из древнейших цивилизаций, долина Нила, фараоны, исламский Каир, современное государство.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gq',
    name: 'Экваториальная Гвинея',
    flag: '🇬🇶',
    region: 'Центральная Африка',
    timeline: '1968 — наши дни',
    core: 'Испанская колония, независимость, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'er',
    name: 'Эритрея',
    flag: '🇪🇷',
    region: 'Восточная Африка',
    timeline: '1993 — наши дни',
    core: 'Эфиопская провинция, независимость, роль в регионе Красного моря.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sz',
    name: 'Эсватини',
    flag: '🇸🇿',
    region: 'Южная Африка',
    timeline: '1968 — наши дни',
    core: 'Британский протекторат Свазиленд, независимость, монархия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'et',
    name: 'Эфиопия',
    flag: '🇪🇹',
    region: 'Восточная Африка',
    timeline: 'ок. 980 до н.э. — наши дни',
    core: 'Одна из древнейших христианских стран, Аксум, независимость, роль в Африке и ООН.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ga',
    name: 'Габон',
    flag: '🇬🇦',
    region: 'Центральная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gm',
    name: 'Гамбия',
    flag: '🇬🇲',
    region: 'Западная Африка',
    timeline: '1965 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gh',
    name: 'Гана',
    flag: '🇬🇭',
    region: 'Западная Африка',
    timeline: '1957 — наши дни',
    core: 'Британская колония Золотой Берег, независимость под руководством Нкрумы, роль в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gn',
    name: 'Гвинея',
    flag: '🇬🇳',
    region: 'Западная Африка',
    timeline: '1958 — наши дни',
    core: 'Французская колония, независимость под руководством Секу Туре, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gw',
    name: 'Гвинея-Бисау',
    flag: '🇬🇼',
    region: 'Западная Африка',
    timeline: '1973 — наши дни',
    core: 'Португальская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ke',
    name: 'Кения',
    flag: '🇰🇪',
    region: 'Восточная Африка',
    timeline: '1963 — наши дни',
    core: 'Британская колония, восстание Мау-Мау, независимость, роль в Восточной Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ls',
    name: 'Лесото',
    flag: '🇱🇸',
    region: 'Южная Африка',
    timeline: '1966 — наши дни',
    core: 'Британский протекторат Басутоленд, независимость, монархия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lr',
    name: 'Либерия',
    flag: '🇱🇷',
    region: 'Западная Африка',
    timeline: '1847 — наши дни',
    core: 'Основанная освобождёнными рабами из США, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ly',
    name: 'Ливия',
    flag: '🇱🇾',
    region: 'Северная Африка',
    timeline: '1951 — наши дни',
    core: 'Итальянская колония, независимость под руководством короля Идриса, Каддафи, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mg',
    name: 'Мадагаскар',
    flag: '🇲🇬',
    region: 'Восточная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, роль в регионе Индийского океана.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mw',
    name: 'Малави',
    flag: '🇲🇼',
    region: 'Южная Африка',
    timeline: '1964 — наши дни',
    core: 'Британский протекторат Ньясаленд, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ml',
    name: 'Мали',
    flag: '🇲🇱',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Французский Судан, независимость, древние цивилизации, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mr',
    name: 'Мавритания',
    flag: '🇲🇷',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, роль в регионе Сахеля.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mu',
    name: 'Маврикий',
    flag: '🇲🇺',
    region: 'Восточная Африка',
    timeline: '1968 — наши дни',
    core: 'Британская и французская колонизация, независимость, роль в Индийском океане.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ma',
    name: 'Марокко',
    flag: '🇲🇦',
    region: 'Северная Африка',
    timeline: '1956 — наши дни',
    core: 'Арабские халифаты, французский и испанский протектораты, независимость, монархия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mz',
    name: 'Мозамбик',
    flag: '🇲🇿',
    region: 'Южная Африка',
    timeline: '1975 — наши дни',
    core: 'Португальская колония, независимость под руководством ФРЕЛИМО, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'na',
    name: 'Намибия',
    flag: '🇳🇦',
    region: 'Южная Африка',
    timeline: '1990 — наши дни',
    core: 'Немецкая колония Южная Африка, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ne',
    name: 'Нигер',
    flag: '🇳🇪',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, роль в регионе Сахеля.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ng',
    name: 'Нигерия',
    flag: '🇳🇬',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Британская колония, независимость, гражданская война в Биафре, нефть, роль в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'rw',
    name: 'Руанда',
    flag: '🇷🇼',
    region: 'Восточная Африка',
    timeline: '1962 — наши дни',
    core: 'Немецкая и бельгийская колонизация, независимость, геноцид 1994 года, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'st',
    name: 'Сан-Томе и Принсипи',
    flag: '🇸🇹',
    region: 'Центральная Африка',
    timeline: '1975 — наши дни',
    core: 'Португальская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sn',
    name: 'Сенегал',
    flag: '🇸🇳',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sc',
    name: 'Сейшельские Острова',
    flag: '🇸🇨',
    region: 'Восточная Африка',
    timeline: '1976 — наши дни',
    core: 'Британская колония, независимость, роль в Индийском океане.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sl',
    name: 'Сьерра-Леоне',
    flag: '🏴',
    region: 'Западная Африка',
    timeline: '1961 — наши дни',
    core: 'Британская колония, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'so',
    name: 'Сомали',
    flag: '🏴',
    region: 'Восточная Африка',
    timeline: '1960 — наши дни',
    core: 'Итальянская и британская колонизация, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'za',
    name: 'Южная Африка',
    flag: '🇿🇦',
    region: 'Южная Африка',
    timeline: '1961 — наши дни',
    core: 'Колонизация, апартеид, борьба Манделы, постапартеидная демократия, роль в Африке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ss',
    name: 'Южный Судан',
    flag: '🇸🇸',
    region: 'Восточная Африка',
    timeline: '2011 — наши дни',
    core: 'Отделение от Судана, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sd',
    name: 'Судан',
    flag: '🇸🇩',
    region: 'Северная Африка',
    timeline: '1956 — наши дни',
    core: 'Британско-египетский кондоминиум, независимость, разделение с Южным Суданом, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tz',
    name: 'Танзания',
    flag: '🇹🇿',
    region: 'Восточная Африка',
    timeline: '1961 — наши дни',
    core: 'Британская колония Танганьика и немецкая Восточная Африка, объединение с Занзибаром, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tg',
    name: 'Того',
    flag: '🇹🇬',
    region: 'Западная Африка',
    timeline: '1960 — наши дни',
    core: 'Французская и немецкая колонизация, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tn',
    name: 'Тунис',
    flag: '🇹🇳',
    region: 'Северная Африка',
    timeline: '1956 — наши дни',
    core: 'Французский протекторат, независимость, арабская весна, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ug',
    name: 'Уганда',
    flag: '🇺🇬',
    region: 'Восточная Африка',
    timeline: '1962 — наши дни',
    core: 'Британский протекторат, независимость, диктатура Иди Амина, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'zm',
    name: 'Замбия',
    flag: '🇿🇲',
    region: 'Южная Африка',
    timeline: '1964 — наши дни',
    core: 'Британский протекторат Северная Родезия, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'zw',
    name: 'Зимбабве',
    flag: '🇿🇼',
    region: 'Южная Африка',
    timeline: '1980 — наши дни',
    core: 'Британская колония Родезия, независимость под руководством Мугабе, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ag',
    name: 'Антигуа и Барбуда',
    flag: '🇦🇬',
    region: 'Карибы',
    timeline: '1981 — наши дни',
    core: 'Британская колония, независимость, роль в регионе Карибского бассейна.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ar',
    name: 'Аргентина',
    flag: '🇦🇷',
    region: 'Южная Америка',
    timeline: '1816 — наши дни',
    core: 'Независимость от Испании, иммиграция, перонизм, роль в Южном конусе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bs',
    name: 'Багамы',
    flag: '🇧🇸',
    region: 'Карибы',
    timeline: '1973 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bb',
    name: 'Барбадос',
    flag: '🇧🇧',
    region: 'Карибы',
    timeline: '1966 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bz',
    name: 'Белиз',
    flag: '🇧🇿',
    region: 'Центральная Америка',
    timeline: '1981 — наши дни',
    core: 'Британская колония Британский Гондурас, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bo',
    name: 'Боливия',
    flag: '🇧🇴',
    region: 'Южная Америка',
    timeline: '1825 — наши дни',
    core: 'Независимость от Испании, роль в регионе, политическая нестабильность.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'br',
    name: 'Бразилия',
    flag: '🇧🇷',
    region: 'Южная Америка',
    timeline: '1822 — наши дни',
    core: 'Португальская колонизация, монархия, республика, индустриализация, роль в Латинской Америке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ca',
    name: 'Канада',
    flag: '🇨🇦',
    region: 'Северная Америка',
    timeline: '1867 — наши дни',
    core: 'Конфедерация, расширение на запад, мультикультурализм, роль в международных организациях.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cl',
    name: 'Чили',
    flag: '🇨🇱',
    region: 'Южная Америка',
    timeline: '1818 — наши дни',
    core: 'Независимость от Испании, диктатура Пиночета, демократизация, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'co',
    name: 'Колумбия',
    flag: '🇨🇴',
    region: 'Южная Америка',
    timeline: '1810 — наши дни',
    core: 'Независимость от Испании, гражданская война, наркокартели, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cr',
    name: 'Коста-Рика',
    flag: '🇨🇷',
    region: 'Центральная Америка',
    timeline: '1821 — наши дни',
    core: 'Независимость от Испании, стабильная демократия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cu',
    name: 'Куба',
    flag: '🇨🇺',
    region: 'Карибы',
    timeline: '1902 — наши дни',
    core: 'Испанская колония, революция Кастро, социализм, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'dm',
    name: 'Доминика',
    flag: '🇩🇲',
    region: 'Карибы',
    timeline: '1978 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'do',
    name: 'Доминиканская Республика',
    flag: '🇩🇴',
    region: 'Карибы',
    timeline: '1844 — наши дни',
    core: 'Независимость от Гаити, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ec',
    name: 'Эквадор',
    flag: '🇪🇨',
    region: 'Южная Америка',
    timeline: '1822 — наши дни',
    core: 'Независимость от Испании, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sv',
    name: 'Сальвадор',
    flag: '🇸🇻',
    region: 'Центральная Америка',
    timeline: '1821 — наши дни',
    core: 'Независимость от Испании, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gd',
    name: 'Гренада',
    flag: '🇬🇩',
    region: 'Карибы',
    timeline: '1974 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gt',
    name: 'Гватемала',
    flag: '🇬🇹',
    region: 'Центральная Америка',
    timeline: '1821 — наши дни',
    core: 'Независимость от Испании, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gy',
    name: 'Гайана',
    flag: '🇬🇾',
    region: 'Южная Америка',
    timeline: '1966 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ht',
    name: 'Гаити',
    flag: '🇭🇹',
    region: 'Карибы',
    timeline: '1804 — наши дни',
    core: 'Независимость от Франции, первая чёрная республика, политическая нестабильность.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'hn',
    name: 'Гондурас',
    flag: '🇭🇳',
    region: 'Центральная Америка',
    timeline: '1821 — наши дни',
    core: 'Независимость от Испании, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'jm',
    name: 'Ямайка',
    flag: '🇯🇲',
    region: 'Карибы',
    timeline: '1962 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mx',
    name: 'Мексика',
    flag: '🇲🇽',
    region: 'Северная Америка',
    timeline: '1810 — наши дни',
    core: 'Независимость от Испании, революция, индустриализация, роль в Латинской Америке.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ni',
    name: 'Никарагуа',
    flag: '🇳🇮',
    region: 'Центральная Америка',
    timeline: '1821 — наши дни',
    core: 'Независимость от Испании, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pa',
    name: 'Панама',
    flag: '🇵🇦',
    region: 'Центральная Америка',
    timeline: '1903 — наши дни',
    core: 'Отделение от Колумбии, Панамский канал, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'py',
    name: 'Парагвай',
    flag: '🇵🇾',
    region: 'Южная Америка',
    timeline: '1811 — наши дни',
    core: 'Независимость от Испании, диктатура Строэсснера, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pe',
    name: 'Перу',
    flag: '🇵🇪',
    region: 'Южная Америка',
    timeline: '1821 — наши дни',
    core: 'Независимость от Испании, империя инков, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kn',
    name: 'Сент-Китс и Невис',
    flag: '🇰🇳',
    region: 'Карибы',
    timeline: '1983 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lc',
    name: 'Сент-Люсия',
    flag: '🇱🇨',
    region: 'Карибы',
    timeline: '1979 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'vc',
    name: 'Сент-Винсент и Гренадины',
    flag: '🇻🇨',
    region: 'Карибы',
    timeline: '1979 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sr',
    name: 'Суринам',
    flag: '🇸🇷',
    region: 'Южная Америка',
    timeline: '1975 — наши дни',
    core: 'Нидерландская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tt',
    name: 'Тринидад и Тобаго',
    flag: '🇹🇹',
    region: 'Карибы',
    timeline: '1962 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'us',
    name: 'США',
    flag: '🇺🇸',
    region: 'Северная Америка',
    timeline: '1776 — наши дни',
    core: 'Революция, конституция, гражданская война, индустриальная мощь, мировая роль.',
    topics: ["Независимость", "Конституция", "Гражданская война", "Холодная война", "Современность"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'uy',
    name: 'Уругвай',
    flag: '🇺🇾',
    region: 'Южная Америка',
    timeline: '1825 — наши дни',
    core: 'Независимость от Бразилии, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 've',
    name: 'Венесуэла',
    flag: '🇻🇪',
    region: 'Южная Америка',
    timeline: '1811 — наши дни',
    core: 'Независимость от Испании, нефть, политическая нестабильность, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'af',
    name: 'Афганистан',
    flag: '🇦🇫',
    region: 'Южная Азия',
    timeline: '1919 — наши дни',
    core: 'Независимость от Великобритании, советская интервенция, талибы, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'am',
    name: 'Армения',
    flag: '🇦🇲',
    region: 'Южный Кавказ',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, конфликт с Азербайджаном, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'az',
    name: 'Азербайджан',
    flag: '🇦🇿',
    region: 'Южный Кавказ',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, нефть, конфликт с Арменией, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bh',
    name: 'Бахрейн',
    flag: '🇧🇭',
    region: 'Ближний Восток',
    timeline: '1971 — наши дни',
    core: 'Британский протекторат, независимость, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bd',
    name: 'Бангладеш',
    flag: '🇧🇩',
    region: 'Южная Азия',
    timeline: '1971 — наши дни',
    core: 'Восточный Пакистан, отделение от Пакистана, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bt',
    name: 'Бутан',
    flag: '🇧🇹',
    region: 'Южная Азия',
    timeline: '1947 — наши дни',
    core: 'Королевство Бутан, независимость от Великобритании, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bn',
    name: 'Бруней',
    flag: '🇧🇳',
    region: 'Юго-Восточная Азия',
    timeline: '1984 — наши дни',
    core: 'Британский протекторат, независимость, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kh',
    name: 'Камбоджа',
    flag: '🇰🇭',
    region: 'Юго-Восточная Азия',
    timeline: '1953 — наши дни',
    core: 'Французская колония, независимость, режим Пол Пота, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cn',
    name: 'Китай',
    flag: '🇨🇳',
    region: 'Восточная Азия',
    timeline: 'ок. 1600 до н.э. — наши дни',
    core: 'Династические циклы, конфуцианская бюрократия, шелковые пути, революции XX века, возвышение современной державы.',
    topics: ["Династии", "Конфуцианство", "Шелковые пути", "Революция", "КНР"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ge',
    name: 'Грузия',
    flag: '🇬🇪',
    region: 'Южный Кавказ',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'in',
    name: 'Индия',
    flag: '🇮🇳',
    region: 'Южная Азия',
    timeline: '1947 — наши дни',
    core: 'Цивилизация долины Инда, ведическая культура, Британская Индия, независимость, роль в мире.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'id',
    name: 'Индонезия',
    flag: '🇮🇩',
    region: 'Юго-Восточная Азия',
    timeline: '1945 — наши дни',
    core: 'Голландская колония, независимость под руководством Сукарно, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ir',
    name: 'Иран',
    flag: '🇮🇷',
    region: 'Западная Азия',
    timeline: 'ок. 550 до н.э. — наши дни',
    core: 'Персидская империя, исламизация, Сефевидская держава, Исламская революция, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'iq',
    name: 'Ирак',
    flag: '🇮🇶',
    region: 'Ближний Восток',
    timeline: '1932 — наши дни',
    core: 'Мандат Великобритании, независимость, диктатура Саддама Хусейна, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'il',
    name: 'Израиль',
    flag: '🇮🇱',
    region: 'Ближний Восток',
    timeline: '1948 — наши дни',
    core: 'Создание еврейского государства, войны с арабскими странами, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'jp',
    name: 'Япония',
    flag: '🇯🇵',
    region: 'Восточная Азия',
    timeline: 'ок. 300 до н.э. — наши дни',
    core: 'Императорская традиция, самурайские режимы, Мэйдзи, империя, технологическая держава.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'jo',
    name: 'Иордания',
    flag: '🇯🇴',
    region: 'Ближний Восток',
    timeline: '1946 — наши дни',
    core: 'Трансиордания, независимость, монархия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kz',
    name: 'Казахстан',
    flag: '🇰🇿',
    region: 'Центральная Азия',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kw',
    name: 'Кувейт',
    flag: '🇰🇼',
    region: 'Ближний Восток',
    timeline: '1961 — наши дни',
    core: 'Британский протекторат, независимость, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kg',
    name: 'Кыргызстан',
    flag: '🇰🇬',
    region: 'Центральная Азия',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'la',
    name: 'Лаос',
    flag: '🇱🇦',
    region: 'Юго-Восточная Азия',
    timeline: '1953 — наши дни',
    core: 'Французская колония, независимость, социалистический период, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lb',
    name: 'Ливан',
    flag: '🇱🇧',
    region: 'Ближний Восток',
    timeline: '1943 — наши дни',
    core: 'Французский мандат, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'my',
    name: 'Малайзия',
    flag: '🇲🇾',
    region: 'Юго-Восточная Азия',
    timeline: '1957 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mv',
    name: 'Мальдивы',
    flag: '🇲🇻',
    region: 'Южная Азия',
    timeline: '1965 — наши дни',
    core: 'Британский протекторат, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mn',
    name: 'Монголия',
    flag: '🇲🇳',
    region: 'Центральная Азия',
    timeline: '1921 — наши дни',
    core: 'Монгольская империя Чингисхана, советский период, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mm',
    name: 'Мьянма',
    flag: '🇲🇲',
    region: 'Юго-Восточная Азия',
    timeline: '1948 — наши дни',
    core: 'Британская колония Бирма, независимость, диктатура, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'np',
    name: 'Непал',
    flag: '🇳🇵',
    region: 'Южная Азия',
    timeline: '1768 — наши дни',
    core: 'Королевство Непал, независимость, монархия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kp',
    name: 'Северная Корея',
    flag: '🇰🇵',
    region: 'Восточная Азия',
    timeline: '1948 — наши дни',
    core: 'Создание КНДР, чучхе, изоляция, ядерная программа, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'om',
    name: 'Оман',
    flag: '🇴🇲',
    region: 'Ближний Восток',
    timeline: '1970 — наши дни',
    core: 'Султанат Оман, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pk',
    name: 'Пакистан',
    flag: '🇵🇰',
    region: 'Южная Азия',
    timeline: '1947 — наши дни',
    core: 'Раздел Индии, гражданская война 1971, ядерная программа, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ps',
    name: 'Палестина',
    flag: '🇵🇸',
    region: 'Ближний Восток',
    timeline: '1988 — наши дни',
    core: 'Наблюдатель ООН, спорная территория, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ph',
    name: 'Филиппины',
    flag: '🇵🇭',
    region: 'Юго-Восточная Азия',
    timeline: '1946 — наши дни',
    core: 'Испанская и американская колонизация, независимость, диктатура Маркоса, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'qa',
    name: 'Катар',
    flag: '🇶🇦',
    region: 'Ближний Восток',
    timeline: '1971 — наши дни',
    core: 'Британский протекторат, независимость, газ, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sa',
    name: 'Саудовская Аравия',
    flag: '🇸🇦',
    region: 'Ближний Восток',
    timeline: '1932 — наши дни',
    core: 'Объединение Неджда, нефть, исламский мир, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sg',
    name: 'Сингапур',
    flag: '🇸🇬',
    region: 'Юго-Восточная Азия',
    timeline: '1965 — наши дни',
    core: 'Британская колония, независимость, экономическое чудо, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'kr',
    name: 'Южная Корея',
    flag: '🇰🇷',
    region: 'Восточная Азия',
    timeline: '1948 — наши дни',
    core: 'Разделение Кореи, экономическое чудо, демократизация, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lk',
    name: 'Шри-Ланка',
    flag: '🇱🇰',
    region: 'Южная Азия',
    timeline: '1948 — наши дни',
    core: 'Британская колония Цейлон, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sy',
    name: 'Сирия',
    flag: '🇸🇾',
    region: 'Ближний Восток',
    timeline: '1946 — наши дни',
    core: 'Французский мандат, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tj',
    name: 'Таджикистан',
    flag: '🇹🇯',
    region: 'Центральная Азия',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'th',
    name: 'Таиланд',
    flag: '🇹🇭',
    region: 'Юго-Восточная Азия',
    timeline: '1238 — наши дни',
    core: 'Сохранение независимости, монархия, буддизм, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tl',
    name: 'Восточный Тимор',
    flag: '🇹🇱',
    region: 'Юго-Восточная Азия',
    timeline: '2002 — наши дни',
    core: 'Португальская и индонезийская оккупация, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tm',
    name: 'Туркменистан',
    flag: '🇹🇲',
    region: 'Центральная Азия',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, газ, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tr',
    name: 'Турция',
    flag: '🇹🇷',
    region: 'Юго-Восточная Европа и Западная Азия',
    timeline: '1923 — наши дни',
    core: 'Османская империя, модернизация Ататюрка, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ae',
    name: 'ОАЭ',
    flag: '🇦🇪',
    region: 'Ближний Восток',
    timeline: '1971 — наши дни',
    core: 'Объединение эмиратов, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'uz',
    name: 'Узбекистан',
    flag: '🇺🇿',
    region: 'Центральная Азия',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'va',
    name: 'Ватикан',
    flag: '🇻🇦',
    region: 'Южная Европа',
    timeline: '1929 — наши дни',
    core: 'Папское государство, наблюдатель ООН, центр католицизма.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'vn',
    name: 'Вьетнам',
    flag: '🇻🇳',
    region: 'Юго-Восточная Азия',
    timeline: '1945 — наши дни',
    core: 'Древние государства, колонизация, разделение, воссоединение, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ye',
    name: 'Йемен',
    flag: '🇾🇪',
    region: 'Ближний Восток',
    timeline: '1990 — наши дни',
    core: 'Объединение Северного и Южного Йемена, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'al',
    name: 'Албания',
    flag: '🇦🇱',
    region: 'Южная Европа',
    timeline: '1912 — наши дни',
    core: 'Независимость от Османской империи, коммунизм, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ad',
    name: 'Андорра',
    flag: '🇦🇩',
    region: 'Южная Европа',
    timeline: '1278 — наши дни',
    core: 'Княжество Андорра, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'at',
    name: 'Австрия',
    flag: '🇦🇹',
    region: 'Центральная Европа',
    timeline: '1955 — наши дни',
    core: 'Австро-Венгерская империя, аншлюс, нейтралитет, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'by',
    name: 'Беларусь',
    flag: '🇧🇾',
    region: 'Восточная Европа',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'be',
    name: 'Бельгия',
    flag: '🇧🇪',
    region: 'Западная Европа',
    timeline: '1830 — наши дни',
    core: 'Независимость от Нидерландов, колониальная империя, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ba',
    name: 'Босния и Герцеговина',
    flag: '🇧🇦',
    region: 'Южная Европа',
    timeline: '1992 — наши дни',
    core: 'Независимость от Югославии, гражданская война, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'bg',
    name: 'Болгария',
    flag: '🇧🇬',
    region: 'Южная Европа',
    timeline: '1908 — наши дни',
    core: 'Независимость от Османской империи, социалистический период, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'hr',
    name: 'Хорватия',
    flag: '🇭🇷',
    region: 'Южная Европа',
    timeline: '1991 — наши дни',
    core: 'Независимость от Югославии, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cy',
    name: 'Кипр',
    flag: '🇨🇾',
    region: 'Южная Европа',
    timeline: '1960 — наши дни',
    core: 'Независимость от Великобритании, разделение, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'cz',
    name: 'Чехия',
    flag: '🇨🇿',
    region: 'Центральная Европа',
    timeline: '1993 — наши дни',
    core: 'Разделение Чехословакии, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'dk',
    name: 'Дания',
    flag: '🇩🇰',
    region: 'Северная Европа',
    timeline: '936 — наши дни',
    core: 'Викинги, монархия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ee',
    name: 'Эстония',
    flag: '🇪🇪',
    region: 'Северная Европа',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'fi',
    name: 'Финляндия',
    flag: '🇫🇮',
    region: 'Северная Европа',
    timeline: '1917 — наши дни',
    core: 'Независимость от России, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'fr',
    name: 'Франция',
    flag: '🇫🇷',
    region: 'Западная Европа',
    timeline: '843 — наши дни',
    core: 'Капетинги, революция, Наполеон, ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'de',
    name: 'Германия',
    flag: '🇩🇪',
    region: 'Центральная Европа',
    timeline: '843 — наши дни',
    core: 'Римская империя, объединение, мировые войны, ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gr',
    name: 'Греция',
    flag: '🇬🇷',
    region: 'Южная Европа',
    timeline: '1821 — наши дни',
    core: 'Независимость от Османской империи, древняя цивилизация, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'hu',
    name: 'Венгрия',
    flag: '🇭🇺',
    region: 'Центральная Европа',
    timeline: '1000 — наши дни',
    core: 'Королевство Венгрия, Австро-Венгрия, социализм, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'is',
    name: 'Исландия',
    flag: '🇮🇸',
    region: 'Северная Европа',
    timeline: '1944 — наши дни',
    core: 'Независимость от Дании, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ie',
    name: 'Ирландия',
    flag: '🇮🇪',
    region: 'Западная Европа',
    timeline: '1922 — наши дни',
    core: 'Независимость от Великобритании, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'it',
    name: 'Италия',
    flag: '🇮🇹',
    region: 'Южная Европа',
    timeline: '1861 — наши дни',
    core: 'Рисорджименто, фашизм, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'xk',
    name: 'Косово',
    flag: '🏳️',
    region: 'Южная Европа',
    timeline: '2008 — наши дни',
    core: 'Спорная территория, частично признанное государство, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lv',
    name: 'Латвия',
    flag: '🇱🇻',
    region: 'Северная Европа',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'li',
    name: 'Лихтенштейн',
    flag: '🇱🇮',
    region: 'Центральная Европа',
    timeline: '1866 — наши дни',
    core: 'Княжество, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lt',
    name: 'Литва',
    flag: '🇱🇹',
    region: 'Северная Европа',
    timeline: '1990 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'lu',
    name: 'Люксембург',
    flag: '🇱🇺',
    region: 'Западная Европа',
    timeline: '1839 — наши дни',
    core: 'Независимость, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mt',
    name: 'Мальта',
    flag: '🇲🇹',
    region: 'Южная Европа',
    timeline: '1964 — наши дни',
    core: 'Британская колония, независимость, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'md',
    name: 'Молдова',
    flag: '🇲🇩',
    region: 'Восточная Европа',
    timeline: '1991 — наши дни',
    core: 'Советская республика, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mc',
    name: 'Монако',
    flag: '🇲🇨',
    region: 'Южная Европа',
    timeline: '1297 — наши дни',
    core: 'Княжество, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'me',
    name: 'Черногория',
    flag: '🇲🇪',
    region: 'Южная Европа',
    timeline: '2006 — наши дни',
    core: 'Независимость от Сербии, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'nl',
    name: 'Нидерланды',
    flag: '🇳🇱',
    region: 'Западная Европа',
    timeline: '1581 — наши дни',
    core: 'Независимость от Испании, колониальная империя, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mk',
    name: 'Северная Македония',
    flag: '🇲🇰',
    region: 'Южная Европа',
    timeline: '1991 — наши дни',
    core: 'Независимость от Югославии, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'no',
    name: 'Норвегия',
    flag: '🇳🇴',
    region: 'Северная Европа',
    timeline: '1905 — наши дни',
    core: 'Независимость от Швеции, нефть, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pl',
    name: 'Польша',
    flag: '🇵🇱',
    region: 'Центральная Европа',
    timeline: '1918 — наши дни',
    core: 'Восстановление после разделов, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pt',
    name: 'Португалия',
    flag: '🇵🇹',
    region: 'Южная Европа',
    timeline: '1139 — наши дни',
    core: 'Ранняя монархия, колониальная империя, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ro',
    name: 'Румыния',
    flag: '🇷🇴',
    region: 'Южная Европа',
    timeline: '1877 — наши дни',
    core: 'Независимость от Османской империи, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ru',
    name: 'Россия',
    flag: '🇷🇺',
    region: 'Восточная Европа и Северная Азия',
    timeline: '882 — наши дни',
    core: 'Киевская Русь, империя, СССР, постсоветский период, роль в мире.',
    topics: ["Русь", "Московское княжество", "Российская империя", "СССР", "1991+"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sm',
    name: 'Сан-Марино',
    flag: '🇸🇲',
    region: 'Южная Европа',
    timeline: '301 — наши дни',
    core: 'Древнейшая республика, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'rs',
    name: 'Сербия',
    flag: '🇷🇸',
    region: 'Южная Европа',
    timeline: '1878 — наши дни',
    core: 'Независимость от Османской империи, Югославия, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sk',
    name: 'Словакия',
    flag: '🇸🇰',
    region: 'Центральная Европа',
    timeline: '1993 — наши дни',
    core: 'Разделение Чехословакии, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'si',
    name: 'Словения',
    flag: '🇸🇮',
    region: 'Южная Европа',
    timeline: '1991 — наши дни',
    core: 'Независимость от Югославии, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'es',
    name: 'Испания',
    flag: '🇪🇸',
    region: 'Южная Европа',
    timeline: '1492 — наши дни',
    core: 'Реконкиста, колониальная империя, роль в ЕС.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'se',
    name: 'Швеция',
    flag: '🇸🇪',
    region: 'Северная Европа',
    timeline: '1523 — наши дни',
    core: 'Великая держава, нейтралитет, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ch',
    name: 'Швейцария',
    flag: '🇨🇭',
    region: 'Центральная Европа',
    timeline: '1291 — наши дни',
    core: 'Конфедерация, нейтралитет, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ua',
    name: 'Украина',
    flag: '🇺🇦',
    region: 'Восточная Европа',
    timeline: '1991 — наши дни',
    core: 'Киевская Русь, СССР, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'gb',
    name: 'Великобритания',
    flag: '🇬🇧',
    region: 'Западная Европа',
    timeline: '927 — наши дни',
    core: 'Нормандия, парламентская монархия, Британская империя, роль в мире.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'va',
    name: 'Ватикан',
    flag: '🇻🇦',
    region: 'Южная Европа',
    timeline: '1929 — наши дни',
    core: 'Папское государство, наблюдатель ООН, центр католицизма.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ab',
    name: 'Абхазия',
    flag: '🏴',
    region: 'Кавказ',
    timeline: '1992 — наши дни',
    core: 'Спорная территория, частично признанное государство, конфликт с Грузией.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'xk',
    name: 'Косово',
    flag: '🏳️',
    region: 'Балканы',
    timeline: '2008 — наши дни',
    core: 'Частично признанное государство, спорная территория, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'nkr',
    name: 'Нагорный Карабах',
    flag: '🏴',
    region: 'Кавказ',
    timeline: '1991 — наши дни',
    core: 'Спорная территория, конфликт между Арменией и Азербайджаном.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'trnc',
    name: 'Северный Кипр',
    flag: '🏴',
    region: 'Средиземноморье',
    timeline: '1983 — наши дни',
    core: 'Частично признанное государство, спорная территория.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ps',
    name: 'Палестина',
    flag: '🇵🇸',
    region: 'Ближний Восток',
    timeline: '1988 — наши дни',
    core: 'Наблюдатель ООН, спорная территория, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sl',
    name: 'Сомалиленд',
    flag: '🏴',
    region: 'Восточная Африка',
    timeline: '1991 — наши дни',
    core: 'Спорная территория, частично признанное государство, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'so',
    name: 'Южная Осетия',
    flag: '🏴',
    region: 'Кавказ',
    timeline: '1991 — наши дни',
    core: 'Спорная территория, частично признанное государство.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tw',
    name: 'Тайвань',
    flag: '🇹🇼',
    region: 'Восточная Азия',
    timeline: '1949 — наши дни',
    core: 'Спорная территория, частично признанное государство, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pmr',
    name: 'Приднестровье',
    flag: '🏳️',
    region: 'Восточная Европа',
    timeline: '1990 — наши дни',
    core: 'Спорная территория, конфликт с Молдовой.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'eh',
    name: 'Западная Сахара',
    flag: '🏳️',
    region: 'Северная Африка',
    timeline: '1976 — наши дни',
    core: 'Спорная территория, конфликт с Марокко.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'au',
    name: 'Австралия',
    flag: '🇦🇺',
    region: 'Океания',
    timeline: '1901 — наши дни',
    core: 'Британская колонизация, федерация, роль в Азиатско-Тихоокеанском регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'fj',
    name: 'Фиджи',
    flag: '🇫🇯',
    region: 'Океания',
    timeline: '1970 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ki',
    name: 'Кирибати',
    flag: '🇰🇮',
    region: 'Океания',
    timeline: '1979 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'mh',
    name: 'Маршалловы Острова',
    flag: '🇲🇭',
    region: 'Океания',
    timeline: '1986 — наши дни',
    core: 'Американская территория под опекой ООН, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'fm',
    name: 'Микронезия',
    flag: '🇫🇲',
    region: 'Океания',
    timeline: '1986 — наши дни',
    core: 'Американская территория под опекой ООН, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'nr',
    name: 'Науру',
    flag: '🇳🇷',
    region: 'Океания',
    timeline: '1968 — наши дни',
    core: 'Немецкая и австралийская колонизация, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'nz',
    name: 'Новая Зеландия',
    flag: '🇳🇿',
    region: 'Океания',
    timeline: '1907 — наши дни',
    core: 'Британская колония, договор Вайтанги, роль в Тихоокеанском регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pw',
    name: 'Палау',
    flag: '🇵🇼',
    region: 'Океания',
    timeline: '1994 — наши дни',
    core: 'Американская территория под опекой ООН, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'pg',
    name: 'Папуа — Новая Гвинея',
    flag: '🇵🇬',
    region: 'Океания',
    timeline: '1975 — наши дни',
    core: 'Австралийская территория, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'ws',
    name: 'Самоа',
    flag: '🇼🇸',
    region: 'Океания',
    timeline: '1962 — наши дни',
    core: 'Немецкая и новозеландская колонизация, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'sb',
    name: 'Соломоновы Острова',
    flag: '🇸🇧',
    region: 'Океания',
    timeline: '1978 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'to',
    name: 'Тонга',
    flag: '🇹🇴',
    region: 'Океания',
    timeline: '1970 — наши дни',
    core: 'Британский протекторат, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'tv',
    name: 'Тувалу',
    flag: '🇹🇻',
    region: 'Океания',
    timeline: '1978 — наши дни',
    core: 'Британская колония, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
  {
    id: 'vu',
    name: 'Вануату',
    flag: '🇻🇺',
    region: 'Океания',
    timeline: '1980 — наши дни',
    core: 'Франко-британский кондоминиум Новые Гебриды, независимость, роль в регионе.',
    topics: ["История", "Политика", "Экономика", "Культура", "География"],
    sources: ["Britannica", "World History Encyclopedia", "National Archives"],
  },
];

export const conflicts = [
  {
    id: 'peloponnesian-war',
    name: 'Пелопоннесская война',
    years: '431–404 до н.э.',
    region: 'Древняя Греция',
    parties: ['Афинский морской союз', 'Пелопоннесский союз'],
    type: 'Античность',
    impact:
      'Подорвала силы греческих полисов, усилила Спарту краткосрочно и подготовила почву для македонского доминирования.',
    learn: ['Причины: страх Спарты перед ростом Афин', 'Источники: Фукидид, Ксенофонт', 'Ключ: осада Сиракуз и истощение Афин'],
  },
  {
    id: 'hundred-years-war',
    name: 'Столетняя война',
    years: '1337–1453',
    region: 'Западная Европа',
    parties: ['Франция', 'Англия'],
    type: 'Средневековье',
    impact:
      'Укрепила французскую монархию, изменила военное дело и ускорила формирование национальных идентичностей.',
    learn: ['Династический спор', 'Лук, артиллерия и крепости', 'Жанна д’Арк и Орлеан'],
  },
  {
    id: 'thirty-years-war',
    name: 'Тридцатилетняя война',
    years: '1618–1648',
    region: 'Центральная Европа',
    parties: ['Габсбурги', 'Протестантские княжества', 'Швеция', 'Франция'],
    type: 'Раннее Новое время',
    impact:
      'Вестфальский мир закрепил принципы суверенитета и изменил баланс сил в Европе.',
    learn: ['Религия и политика', 'Демографический ущерб', 'Вестфальская система'],
  },
  {
    id: 'napoleonic-wars',
    name: 'Наполеоновские войны',
    years: '1803–1815',
    region: 'Европа и Атлантика',
    parties: ['Французская империя', 'Антифранцузские коалиции'],
    type: 'Новое время',
    impact:
      'Распространили правовые и административные реформы, перекроили карту Европы и усилили национализм.',
    learn: ['Кодекс Наполеона', 'Континентальная блокада', '1812 и Ватерлоо'],
  },
  {
    id: 'world-war-i',
    name: 'Первая мировая война',
    years: '1914–1918',
    region: 'Глобальный конфликт',
    parties: ['Антанта', 'Центральные державы'],
    type: 'Мировая война',
    impact:
      'Распад империй, Версальская система, революции и политические напряжения межвоенного периода.',
    learn: ['Союзные блоки', 'Позиционная война', 'Тотальная мобилизация', 'Последствия Версаля'],
  },
  {
    id: 'world-war-ii',
    name: 'Вторая мировая война',
    years: '1939–1945',
    region: 'Глобальный конфликт',
    parties: ['Союзники', 'Ось'],
    type: 'Мировая война',
    impact:
      'Создание ООН, начало холодной войны, деколонизация, новый международный порядок и память о Холокосте.',
    learn: ['Причины ревизионизма', 'Блицкриг и тотальная война', 'Восточный фронт', 'Тихоокеанский театр'],
  },
  {
    id: 'cold-war',
    name: 'Холодная война',
    years: '1947–1991',
    region: 'Глобальная система',
    parties: ['США и союзники', 'СССР и союзники'],
    type: 'Идеологическое противостояние',
    impact:
      'Определила политику второй половины XX века: блоки, прокси-конфликты, ядерное сдерживание и космическую гонку.',
    learn: ['Доктрина Трумэна', 'Берлин', 'Корея и Вьетнам', 'Карибский кризис', 'Разрядка'],
  },
  {
    id: 'first-chechen-war',
    name: 'Первая чеченская война',
    years: '1994–1996',
    region: 'Северный Кавказ, Чечня',
    parties: ['Российская Федерация', 'Чеченская Республика Ичкерия'],
    type: 'Постсоветский конфликт',
    aliases: ['Чечня', 'Чеченская война', 'Грозный', 'Ичкерия', 'Северный Кавказ'],
    impact:
      'Стала одним из самых тяжелых конфликтов постсоветского пространства, привела к большим человеческим потерям, разрушению Грозного и Хасавюртовским соглашениям.',
    learn: ['Распад СССР и кризис федерализма', 'Штурм Грозного', 'Партизанская война', 'Хасавюртовские соглашения', 'Проблема источников и памяти'],
    keyMoments: [
      { date: '1991', title: 'Провозглашение независимости', text: 'Руководство Джохара Дудаева заявило о выходе Чечни из состава России; Москва это не признала.', status: 'спорная правовая оценка' },
      { date: '11.12.1994', title: 'Ввод федеральных войск', text: 'Начало масштабной военной операции Российской Федерации на территории Чечни.', status: 'подтверждено' },
      { date: '1994–1995', title: 'Бои за Грозный', text: 'Тяжёлые городские бои и массированные обстрелы привели к большим потерям среди военных и гражданских.', status: 'подтверждено, оценки потерь различаются' },
      { date: '08.1996', title: 'Хасавюртовские соглашения', text: 'Стороны договорились о прекращении огня и отложили вопрос окончательного статуса Чечни.', status: 'подтверждено' },
    ],
    perspectives: [
      { side: 'Федеральная российская позиция', thesis: 'Операция объяснялась восстановлением конституционного порядка, территориальной целостности и борьбой с вооружёнными формированиями.', caution: 'Это позиция одной стороны конфликта; её нужно проверять по документам, действиям войск и нормам международного гуманитарного права.' },
      { side: 'Чеченская сепаратистская позиция', thesis: 'Конфликт трактовался как война за независимость и сопротивление внешнему военному вмешательству.', caution: 'Это позиция другой стороны; внутри Чечни также были разные политические группы и интересы.' },
      { side: 'Правозащитная и гуманитарная оценка', thesis: 'Правозащитные организации фиксировали нарушения со стороны обеих сторон, отдельно выделяя неизбирательное применение силы, заложников, пытки и обращения с пленными.', caution: 'Сильнее опирается на свидетельства, полевые интервью и сопоставление эпизодов, но тоже требует проверки методики и контекста.' },
    ],
    factCheck: [
      { claim: 'Война шла между РФ и структурами Чеченской Республики Ичкерия.', assessment: 'высокая достоверность', explanation: 'Совпадает в энциклопедических, академических и правозащитных описаниях.' },
      { claim: 'Гражданские потери были очень большими.', assessment: 'высокая достоверность, точные числа спорны', explanation: 'Разные источники дают разные оценки; важно указывать диапазоны и источник методики.' },
      { claim: 'Только одна сторона совершала нарушения.', assessment: 'упрощение / вероятный миф', explanation: 'Правозащитные отчёты фиксируют нарушения у обеих сторон, но масштаб, характер и ответственность по эпизодам различаются.' },
    ],
    sourcePack: {
      summary: 'Для этой темы лучше сочетать энциклопедию, правозащитные отчёты, документы международных организаций, академические исследования и позиции сторон. Один источник не даёт полной картины.',
      sources: [
        { title: 'Human Rights Watch — Chechnya: Report to the 1996 OSCE Review Conference', url: 'https://www.refworld.org/reference/countryrep/hrw/1996/en/22299', type: 'правозащитный отчёт', reliability: 'высокая', stance: 'фокус на нарушениях прав человека', note: 'Полезен для проверки конкретных эпизодов, задержаний, ответственности и свидетельств.' },
        { title: 'Human Rights Watch — Russia: Partisan War in Chechnya, 1995 PDF', url: 'https://www.hrw.org/reports/pdfs/r/russia/russia955.pdf', type: 'полевой отчёт', reliability: 'высокая', stance: 'правозащитная перспектива', note: 'Содержит свидетельства беженцев и описание событий в Самашках, Грозном и других районах.' },
        { title: 'Encyclopaedia Britannica — Chechnya', url: 'https://www.britannica.com/place/Chechnya', type: 'энциклопедия', reliability: 'средне-высокая', stance: 'обзорная нейтральная', note: 'Хорошо для первого ориентирования, но недостаточно для спорных деталей.' },
        { title: 'Wikipedia — First Chechen War', url: 'https://en.wikipedia.org/wiki/First_Chechen_War', type: 'агрегатор со ссылками', reliability: 'средняя', stance: 'зависит от качества ссылок', note: 'Использовать как навигатор по библиографии, а не как окончательное доказательство.' },
      ],
    },
  },
  {
    id: 'second-chechen-war',
    name: 'Вторая чеченская война',
    years: '1999–2009',
    region: 'Северный Кавказ, Чечня',
    parties: ['Российская Федерация', 'Чеченские вооруженные формирования'],
    type: 'Постсоветский конфликт',
    aliases: ['Чечня', 'Чеченская война', 'Контртеррористическая операция', 'Грозный', 'Северный Кавказ'],
    impact:
      'Изменила политическую и силовую архитектуру России начала XXI века, усилила федеральный контроль над регионом и оставила сложное наследие безопасности, прав человека и восстановления.',
    learn: ['Дагестан 1999 года', 'Взрывы домов и начало кампании', 'Второй штурм Грозного', 'Переход к контрпартизанской фазе', 'Восстановление и политическая интеграция'],
    keyMoments: [
      { date: '08.1999', title: 'Вторжение боевиков в Дагестан', text: 'Вооружённые группы вошли в Дагестан, что стало одним из непосредственных поводов к новой кампании.', status: 'подтверждено' },
      { date: '09.1999', title: 'Взрывы жилых домов', text: 'Серия терактов в российских городах стала важнейшим политическим и общественным контекстом начала войны; тема остаётся предметом споров и версий.', status: 'факт взрывов подтверждён, интерпретации спорны' },
      { date: '1999–2000', title: 'Второй штурм Грозного', text: 'Федеральные силы установили контроль над столицей после тяжёлых боёв и разрушений.', status: 'подтверждено' },
      { date: '2000–2009', title: 'Контрпартизанская фаза', text: 'Конфликт перешёл в режим операций против подполья, похищений, терактов, зачисток и политической интеграции региона.', status: 'подтверждено, оценки различаются' },
    ],
    perspectives: [
      { side: 'Федеральная российская позиция', thesis: 'Кампания описывалась как контртеррористическая операция после Дагестана и терактов 1999 года.', caution: 'Нужно отделять подтверждённые события от политических интерпретаций и проверять конкретные обвинения.' },
      { side: 'Чеченская / антифедеральная позиция', thesis: 'Часть участников и сторонников сопротивления трактовала войну как продолжение борьбы против силового контроля Москвы.', caution: 'Эта позиция неоднородна: националистические, исламистские, криминальные и местные интересы могли пересекаться.' },
      { side: 'Международная правозащитная перспектива', thesis: 'Фокус на защите гражданских лиц, исчезновениях, внесудебных казнях, пытках, терактах и ответственности командования.', caution: 'Даёт важную проверку фактов по жертвам, но должна сопоставляться с судебными документами и независимыми исследованиями.' },
    ],
    factCheck: [
      { claim: 'Война была только борьбой с терроризмом.', assessment: 'неполная формулировка', explanation: 'Контртеррористический компонент был важным, но конфликт имел политические, постсоветские, национальные и правовые причины.' },
      { claim: 'Все события 1999 года имеют одну бесспорную интерпретацию.', assessment: 'спорно', explanation: 'Факты многих событий известны, но мотивы, ответственность и политическое использование некоторых эпизодов остаются предметом дискуссий.' },
      { claim: 'Мирное население сильно пострадало.', assessment: 'высокая достоверность', explanation: 'Это подтверждается правозащитными отчётами, журналистскими расследованиями и исследованиями, хотя цифры и ответственность по эпизодам требуют уточнения.' },
    ],
    sourcePack: {
      summary: 'Для второй кампании особенно важно разделять: доказанные события, официальные заявления, версии сторон, судебные решения и правозащитные расследования.',
      sources: [
        { title: 'Human Rights Watch — Russian Atrocities in Chechnya Detailed', url: 'https://www.hrw.org/news/2000/06/01/russian-atrocities-chechnya-detailed', type: 'правозащитный отчёт', reliability: 'высокая', stance: 'права человека', note: 'Подробно описывает эпизоды насилия против гражданских в районе Новые Алды.' },
        { title: 'Sciences Po — Massacres of Civilians in Chechnya', url: 'https://www.sciencespo.fr/mass-violence-war-massacre-resistance/en/document/massacres-civilians-chechnya.html', type: 'академическая справка', reliability: 'высокая', stance: 'исследовательская', note: 'Сводит несколько правозащитных и академических источников по массовому насилию.' },
        { title: 'Encyclopaedia Britannica — Chechnya', url: 'https://www.britannica.com/place/Chechnya', type: 'энциклопедия', reliability: 'средне-высокая', stance: 'обзорная', note: 'Подходит для общего контекста региона и конфликтов.' },
        { title: 'Wikipedia — Second Chechen War', url: 'https://en.wikipedia.org/wiki/Second_Chechen_War', type: 'агрегатор со ссылками', reliability: 'средняя', stance: 'навигатор по источникам', note: 'Использовать как список ссылок, а утверждения проверять по первоисточникам.' },
      ],
    },
  },
  {
    id: 'decolonization-conflicts',
    name: 'Войны деколонизации',
    years: '1945–1975',
    region: 'Азия и Африка',
    parties: ['Колониальные державы', 'Национально-освободительные движения'],
    type: 'Деколонизация',
    impact:
      'Появление десятков новых государств, переосмысление суверенитета и новые линии региональных конфликтов.',
    learn: ['Индокитай', 'Алжир', 'Кения', 'Глобальный Юг и ООН'],
  },
];

export const sourceGroups = [
  {
    title: 'Энциклопедии и справочники',
    items: [
      { name: 'World History Encyclopedia', url: 'https://www.worldhistory.org/', note: 'Статьи, карты, иллюстрации, библиографии.' },
      { name: 'Encyclopaedia Britannica', url: 'https://www.britannica.com/', note: 'Проверенные обзорные статьи и биографии.' },
      { name: 'Internet Encyclopedia of Ukraine', url: 'https://www.encyclopediaofukraine.com/', note: 'Региональная история Восточной Европы.' },
    ],
  },
  {
    title: 'Архивы и первоисточники',
    items: [
      { name: 'Library of Congress', url: 'https://www.loc.gov/', note: 'Документы, карты, фотографии, газеты.' },
      { name: 'National Archives', url: 'https://www.archives.gov/', note: 'Государственные документы США и образовательные коллекции.' },
      { name: 'Europeana', url: 'https://www.europeana.eu/', note: 'Европейские культурные и архивные коллекции.' },
      { name: 'Gallica BnF', url: 'https://gallica.bnf.fr/', note: 'Французские книги, карты и рукописи.' },
    ],
  },
  {
    title: 'Карты, визуализации, музеи',
    items: [
      { name: 'David Rumsey Map Collection', url: 'https://www.davidrumsey.com/', note: 'Исторические карты высокого качества.' },
      { name: 'The Metropolitan Museum of Art', url: 'https://www.metmuseum.org/art/collection', note: 'Артефакты, эссе и хронологии искусства.' },
      { name: 'Smithsonian', url: 'https://www.si.edu/', note: 'Музейные материалы и образовательные ресурсы.' },
    ],
  },
  {
    title: 'Академические инструменты',
    items: [
      { name: 'JSTOR Daily', url: 'https://daily.jstor.org/', note: 'Популярные статьи на основе академических исследований.' },
      { name: 'Google Scholar', url: 'https://scholar.google.com/', note: 'Поиск научных публикаций.' },
      { name: 'CORE', url: 'https://core.ac.uk/', note: 'Открытые академические тексты.' },
    ],
  },
];

export const studyPaths = [
  {
    title: 'Быстрый старт: мировая история за 7 дней',
    level: 'Новичок',
    steps: ['Эпохи и карта времени', 'Древние цивилизации', 'Средневековые сети', 'Океанические империи', 'Революции', 'Мировые войны', 'Холодная война и современность'],
  },
  {
    title: 'Военные конфликты и причины войн',
    level: 'Средний',
    steps: ['Типы причин', 'Экономика войны', 'Союзы и баланс сил', 'Технологии', 'Гражданское население', 'Мирные договоры', 'Память и последствия'],
  },
  {
    title: 'История страны: исследовательский шаблон',
    level: 'Практика',
    steps: ['География', 'Периодизация', 'Политические институты', 'Экономика', 'Культура', 'Войны и дипломатия', 'Источники и историография'],
  },
];

export const glossary = [
  'империя',
  'суверенитет',
  'колониализм',
  'революция',
  'индустриализация',
  'национализм',
  'холодная война',
  'деколонизация',
  'модернизация',
  'дипломатия',
];
